<img src='./img/intel-logo.jpg' width=50%, Fig1> 

# NumPy Basic Lecture02 - NumPy I/O 및 배열연산

<img src='./img/numpy-logo.jpg' width=50%>

<div align='right'>성  민  석 (Minsuk  Sung)</div>
<div align='right'>류  회  성 (Hoesung Ryu)</div>

<h1>강의목차<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-입출력" data-toc-modified-id="NumPy-입출력-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy 입출력</a></span><ul class="toc-item"><li><span><a href="#np.save" data-toc-modified-id="np.save-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>np.save</a></span></li><li><span><a href="#np.savez" data-toc-modified-id="np.savez-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>np.savez</a></span></li><li><span><a href="#np.load" data-toc-modified-id="np.load-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>np.load</a></span></li><li><span><a href="#np.loadtxt" data-toc-modified-id="np.loadtxt-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>np.loadtxt</a></span></li><li><span><a href="#np.savetxt" data-toc-modified-id="np.savetxt-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>np.savetxt</a></span></li></ul></li><li><span><a href="#NumPy-배열연산" data-toc-modified-id="NumPy-배열연산-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NumPy 배열연산</a></span><ul class="toc-item"><li><span><a href="#배열-일반-연산" data-toc-modified-id="배열-일반-연산-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>배열 일반 연산</a></span><ul class="toc-item"><li><span><a href="#산술-연산" data-toc-modified-id="산술-연산-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>산술 연산</a></span><ul class="toc-item"><li><span><a href="#덧셈" data-toc-modified-id="덧셈-2.1.1.1"><span class="toc-item-num">2.1.1.1&nbsp;&nbsp;</span>덧셈</a></span></li><li><span><a href="#뺄셈" data-toc-modified-id="뺄셈-2.1.1.2"><span class="toc-item-num">2.1.1.2&nbsp;&nbsp;</span>뺄셈</a></span></li><li><span><a href="#곱셈" data-toc-modified-id="곱셈-2.1.1.3"><span class="toc-item-num">2.1.1.3&nbsp;&nbsp;</span>곱셈</a></span></li><li><span><a href="#나눗셈" data-toc-modified-id="나눗셈-2.1.1.4"><span class="toc-item-num">2.1.1.4&nbsp;&nbsp;</span>나눗셈</a></span></li><li><span><a href="#지수" data-toc-modified-id="지수-2.1.1.5"><span class="toc-item-num">2.1.1.5&nbsp;&nbsp;</span>지수</a></span></li><li><span><a href="#로그" data-toc-modified-id="로그-2.1.1.6"><span class="toc-item-num">2.1.1.6&nbsp;&nbsp;</span>로그</a></span></li><li><span><a href="#제곱근" data-toc-modified-id="제곱근-2.1.1.7"><span class="toc-item-num">2.1.1.7&nbsp;&nbsp;</span>제곱근</a></span></li><li><span><a href="#삼각함수-sin" data-toc-modified-id="삼각함수-sin-2.1.1.8"><span class="toc-item-num">2.1.1.8&nbsp;&nbsp;</span>삼각함수 sin</a></span></li><li><span><a href="#삼각함수-cos" data-toc-modified-id="삼각함수-cos-2.1.1.9"><span class="toc-item-num">2.1.1.9&nbsp;&nbsp;</span>삼각함수 cos</a></span></li><li><span><a href="#삼각함수-tan" data-toc-modified-id="삼각함수-tan-2.1.1.10"><span class="toc-item-num">2.1.1.10&nbsp;&nbsp;</span>삼각함수 tan</a></span></li><li><span><a href="#내적-(dot-product)" data-toc-modified-id="내적-(dot-product)-2.1.1.11"><span class="toc-item-num">2.1.1.11&nbsp;&nbsp;</span>내적 (dot product)</a></span></li></ul></li><li><span><a href="#비교-연산" data-toc-modified-id="비교-연산-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>비교 연산</a></span><ul class="toc-item"><li><span><a href="#배열의-요소별-비교-(Element-wise)" data-toc-modified-id="배열의-요소별-비교-(Element-wise)-2.1.2.1"><span class="toc-item-num">2.1.2.1&nbsp;&nbsp;</span>배열의 요소별 비교 (Element-wise)</a></span></li><li><span><a href="#배열-비교-(Array-wise)" data-toc-modified-id="배열-비교-(Array-wise)-2.1.2.2"><span class="toc-item-num">2.1.2.2&nbsp;&nbsp;</span>배열 비교 (Array-wise)</a></span></li></ul></li><li><span><a href="#집계-연산" data-toc-modified-id="집계-연산-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>집계 연산</a></span><ul class="toc-item"><li><span><a href="#np.sum" data-toc-modified-id="np.sum-2.1.3.1"><span class="toc-item-num">2.1.3.1&nbsp;&nbsp;</span>np.sum</a></span></li><li><span><a href="#np.min" data-toc-modified-id="np.min-2.1.3.2"><span class="toc-item-num">2.1.3.2&nbsp;&nbsp;</span>np.min</a></span></li><li><span><a href="#np.max" data-toc-modified-id="np.max-2.1.3.3"><span class="toc-item-num">2.1.3.3&nbsp;&nbsp;</span>np.max</a></span></li><li><span><a href="#np.cumsum" data-toc-modified-id="np.cumsum-2.1.3.4"><span class="toc-item-num">2.1.3.4&nbsp;&nbsp;</span>np.cumsum</a></span></li><li><span><a href="#np.mean" data-toc-modified-id="np.mean-2.1.3.5"><span class="toc-item-num">2.1.3.5&nbsp;&nbsp;</span>np.mean</a></span></li><li><span><a href="#np.median" data-toc-modified-id="np.median-2.1.3.6"><span class="toc-item-num">2.1.3.6&nbsp;&nbsp;</span>np.median</a></span></li><li><span><a href="#np.corrcoef" data-toc-modified-id="np.corrcoef-2.1.3.7"><span class="toc-item-num">2.1.3.7&nbsp;&nbsp;</span>np.corrcoef</a></span></li><li><span><a href="#np.std" data-toc-modified-id="np.std-2.1.3.8"><span class="toc-item-num">2.1.3.8&nbsp;&nbsp;</span>np.std</a></span></li></ul></li></ul></li><li><span><a href="#브로드캐스팅" data-toc-modified-id="브로드캐스팅-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>브로드캐스팅</a></span></li><li><span><a href="#백터연산" data-toc-modified-id="백터연산-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>백터연산</a></span></li></ul></li><li><span><a href="#NumPy-배열복사" data-toc-modified-id="NumPy-배열복사-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>NumPy 배열복사</a></span></li><li><span><a href="#NumPy-배열-정렬" data-toc-modified-id="NumPy-배열-정렬-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>NumPy 배열 정렬</a></span></li><li><span><a href="#Reference" data-toc-modified-id="Reference-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reference</a></span></li></ul></div>

In [1]:
import numpy as np

In [2]:
np.random.seed(1234) # 재현성을 위하여

---

## NumPy 입출력

NumPy는 배열 객체를 바이너리 파일 혹은 텍스트 파일에 저장하고 로딩하는 기능을 제공합니다.

|함수명|기능|파일포맷|
|---|---|---|
|np.`save`()|	NumPy 배열 객체 1개를 파일에 저장|	바이너리
|np.`savez`()|	NumPy 배열 객체 복수개를 파일에 저장|	바이너리
|np.`load`()|	NumPy 배열 저장 파일로 부터 객체 로딩|	바이너리
|np.`loadtxt`()|	텍스트 파일로 부터 배열 로딩|	텍스트
|np.`savetxt`()|	텍스트 파일에 NumPy 배열 객체 저장|	텍스트

In [3]:
a = np.random.randint(0, 10, (2, 3))
a

array([[3, 6, 5],
       [4, 8, 9]])

In [4]:
b = np.random.randint(0, 10, (2, 3))
b

array([[1, 7, 9],
       [6, 8, 0]])

### np.save

> np.save : 배열 객체 저장

- np.save 함수를 이용하여 배열 객체를 파일로 저장할 수 있습니다.
- np.save: 1개 배열 저장, 확장자: npy

배열 저장 파일은 바이너리 형태입니다.

In [5]:
# 배열 하나 저장
np.save("./data/array_a", a)

In [6]:
!ls -al data/array_a*

-rw-rw-r-- 1 minsuk minsuk 176 Dec  3 02:29 data/array_a.npy
-rw-rw-r-- 1 minsuk minsuk 602 Dec  3 01:43 data/array_ab.npz


### np.savez

> np.savez : 배열 객체 저장

- np.savez: 복수 배열을 1개의 파일에 저장, 확장자: npz

배열 저장 파일은 바이너리 형태입니다.

In [7]:
# 배열 2개 저장
np.savez("./data/array_ab", a, b)

In [8]:
!ls -al data/array_ab*

-rw-rw-r-- 1 minsuk minsuk 602 Dec  3 02:29 data/array_ab.npz


### np.load

> np.load : npy와 npz 파일을 읽어옴

In [9]:
np.load("./data/array_a.npy")

array([[3, 6, 5],
       [4, 8, 9]])

In [10]:
npzfiles = np.load("./data/array_ab.npz")
npzfiles.files

['arr_0', 'arr_1']

In [11]:
npzfiles['arr_0']

array([[3, 6, 5],
       [4, 8, 9]])

In [12]:
npzfiles['arr_1']

array([[1, 7, 9],
       [6, 8, 0]])

### np.loadtxt

> np.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)
- fname: 파일명
- dtype: 데이터 타입
- comments: comment 시작 부호
- delimiter: 구분자
- skiprows: 제외 라인 수(header 제거용)

텍스트 파일을 np.loadtxt 로 로딩 할 수 있습니다.

In [13]:
# 데이터 파일 위치
!ls -al ./data/sample.txt

-rw-rw-r-- 1 minsuk minsuk 11 Dec  3 01:50 ./data/sample.txt


In [14]:
# 데이터 파일 내용
!cat ./data/sample.txt

1,2,3,4,5,6

In [15]:
np.loadtxt("./data/sample.txt",delimiter=',',dtype=np.int)

array([1, 2, 3, 4, 5, 6])

### np.savetxt

> np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')

- 배열 객체 텍스트 파일로 저장
- np.savetxt 함수를 이용하여 배열 객체를 텍스트 파일로 저장할 수 있습니다.

In [16]:
data = np.random.random((3, 4))
data

array([[0.48683344, 0.33101543, 0.80263957, 0.09825194],
       [0.05599345, 0.44266265, 0.02214391, 0.29072855],
       [0.24639444, 0.73828677, 0.88922613, 0.9871393 ]])

In [17]:
np.savetxt("./data/saved_sample.csv", data, delimiter=",")

In [18]:
#파일 조회
!ls -al ./data/saved_sample.csv

-rw-rw-r-- 1 minsuk minsuk 300 Dec  3 02:29 ./data/saved_sample.csv


In [19]:
#파일 내용 확인
!cat ./data/saved_sample.csv

4.868334433694402330e-01,3.310154282502980605e-01,8.026395691204871730e-01,9.825193555054201333e-02
5.599344896587099552e-02,4.426626489592228042e-01,2.214391360302725431e-02,2.907285532552091878e-01
2.463944432503429871e-01,7.382867680147005007e-01,8.892261317028197221e-01,9.871393022598624611e-01


---

## NumPy 배열연산

### 배열 일반 연산

NumPy는 기본 연산자를 연산자 재정의하여 배열(행렬) 연산에 대한 직관적으로 표현을 강화하였습니다. 모든 산술 연산 함수는 np 모듈에 포함되어 있습니다.

In [20]:
# arange로 1부터 10 미만의 범위에서 1씩 증가하는 배열 생성
# 배열의 shape을 (3, 3)으로 지정
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# arange로 9부터 0까지 범위에서 1씩 감소하는 배열 생성
# 배열의 shape을 (3, 3)으로 지정
b = np.arange(9, 0, -1).reshape(3, 3)
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

> 주의해야할 점 : 기본적으로 배열의 연산에서는 **모두 원소별(pairwise) 연산**입니다.

####  산술 연산

##### 덧셈

In [22]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

##### 뺄셈

In [23]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

##### 곱셈

주의해야할건 행렬곱(dot product)이 아닌 원소별(pairwise) 곱셈입니다.

In [24]:
a*b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [25]:
np.multiply(a, b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

##### 나눗셈

In [26]:
a / b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [27]:
np.divide(a, b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

##### 지수

In [28]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

##### 로그

In [29]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

##### 제곱근

In [30]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

##### 삼각함수 sin

In [31]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

##### 삼각함수 cos

In [32]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

##### 삼각함수 tan

In [33]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

##### 내적 (dot product)

In [34]:
np.dot(a, b)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

#### 비교 연산

##### 배열의 요소별 비교 (Element-wise)

> 기본 연산자를 이용하여 요소별 비교를 할 수 있습니다.

In [35]:
a == b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [36]:
a > b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

##### 배열 비교 (Array-wise)

> 두 배열 전체는 np.array_equal 함수를 사용하여 비교합니다.

In [37]:
np.array_equal(a, b)

False

#### 집계 연산

NumPy의 모든 집계 함수는 집계 함수는 **`AXIS`를 기준으로 계산**됩니다. 집계함수에 AXIS를 지정하지 않으면 axis=None입니다. axis=None, 0, 1은 다음과 같은 기준으로 생각할 수 있습니다.

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### np.sum

> 지정된 axis를 기준으로 요소의 합을 반환합니다.

In [39]:
a.sum()

45

In [40]:
np.sum(a)

45

In [41]:
np.sum(a, axis=0) # 열 기준

array([12, 15, 18])

In [42]:
a.sum(axis=1) # 행 기준

array([ 6, 15, 24])

##### np.min

> 지정된 axis를 기준으로 요소의 최소값을 반환합니다.

In [43]:
a.min()

1

In [44]:
np.min(a)

1

In [45]:
np.min(a, axis=0)

array([1, 2, 3])

In [46]:
a.min(axis=1)

array([1, 4, 7])

##### np.max

> 지정된 axis를 기준으로 요소의 최대값을 반환합니다.

In [47]:
a.max()

9

In [48]:
np.max(a)

9

In [49]:
np.max(a, axis=0)

array([7, 8, 9])

In [50]:
a.max(axis=1)

array([3, 6, 9])

##### np.cumsum

> 지정된 axis를 기준으로 각 요소의 누적 합의 결과를 반환합니다.

In [51]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [52]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [53]:
np.cumsum(a, axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [54]:
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

##### np.mean

> 지정된 axis를 기준으로 요소의 평균을 반환합니다.

In [55]:
a.mean()

5.0

In [56]:
np.mean(a)

5.0

In [57]:
np.mean(a, axis=0)

array([4., 5., 6.])

In [58]:
a.mean(axis=1)

array([2., 5., 8.])

##### np.median

> 지정된 axis를 기준으로 요소의 중앙값을 반환합니다.

In [59]:
np.median(a)

5.0

##### np.corrcoef

In [60]:
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### np.std

> 지정된 axis를 기준으로 요소의 표준 편차를 계산합니다.

In [61]:
a.std()

2.581988897471611

In [62]:
np.std(a)

2.581988897471611

In [63]:
np.std(a, axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [64]:
a.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### 브로드캐스팅

Shape이 같은 두 배열에 대한 이항 연산은 배열의 요소별로 수행됩니다. **두 배열 간의 Shape이 다를 경우** 두 배열 간의 형상을 맞추는 아래와 같은 Broadcasting 과정을 거칩니다.

<img src='./img/numpy-broadcasting.png'>
Ref : https://mathematica.stackexchange.com/questions/99171/how-to-implement-the-general-array-broadcasting-method-from-numpy

### 백터연산

---

## NumPy 배열복사

---

## NumPy 배열 정렬

---

## Reference

- https://www.intel.com
- https://numpy.org/
- https://github.com/rougier/numpy-tutorial
- https://github.com/rougier/numpy-100
- http://aikorea.org/cs231n/python-numpy-tutorial/
- http://riseshia.github.io/2017/01/30/numpy-tutorial-with-code.html
- https://datascienceschool.net/view-notebook/24e43f9df9ec4abab15e32e68e982cc1/
- http://taewan.kim/post/numpy_cheat_sheet/