<img src='./img/intel-logo.jpg' width=50%, Fig1> 

# NumPy Basic Lecture02 - NumPy I/O 및 배열연산

<img src='./img/numpy-logo.jpg' width=50%>

<div align='right'>성  민  석 (Minsuk  Sung)</div>
<div align='right'>류  회  성 (Hoesung Ryu)</div>

<h1>강의목차<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-배열복사" data-toc-modified-id="NumPy-배열복사-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy 배열복사</a></span></li><li><span><a href="#NumPy-배열-정렬" data-toc-modified-id="NumPy-배열-정렬-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NumPy 배열 정렬</a></span></li><li><span><a href="#서브셋,-슬라이싱,-인덱싱" data-toc-modified-id="서브셋,-슬라이싱,-인덱싱-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>서브셋, 슬라이싱, 인덱싱</a></span><ul class="toc-item"><li><span><a href="#요소-선택" data-toc-modified-id="요소-선택-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>요소 선택</a></span><ul class="toc-item"><li><span><a href="#1-차원-배열-요소-참조-및-변경" data-toc-modified-id="1-차원-배열-요소-참조-및-변경-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>1 차원 배열 요소 참조 및 변경</a></span></li><li><span><a href="#2-차원-배열-요소-참조-및-변경" data-toc-modified-id="2-차원-배열-요소-참조-및-변경-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>2 차원 배열 요소 참조 및 변경</a></span></li><li><span><a href="#3-차원-배열-요소-참조-및-변경" data-toc-modified-id="3-차원-배열-요소-참조-및-변경-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>3 차원 배열 요소 참조 및 변경</a></span></li></ul></li><li><span><a href="#슬라이싱" data-toc-modified-id="슬라이싱-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>슬라이싱</a></span><ul class="toc-item"><li><span><a href="#슬라이싱-업데이트" data-toc-modified-id="슬라이싱-업데이트-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>슬라이싱 업데이트</a></span></li></ul></li><li><span><a href="#불린-인덱싱(Boolean-Indexing)" data-toc-modified-id="불린-인덱싱(Boolean-Indexing)-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>불린 인덱싱(Boolean Indexing)</a></span></li><li><span><a href="#팬시-인덱싱(Fancy-Indexing)" data-toc-modified-id="팬시-인덱싱(Fancy-Indexing)-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>팬시 인덱싱(Fancy Indexing)</a></span></li></ul></li><li><span><a href="#배열-변환" data-toc-modified-id="배열-변환-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>배열 변환</a></span><ul class="toc-item"><li><span><a href="#전치(Transpose)" data-toc-modified-id="전치(Transpose)-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>전치(Transpose)</a></span></li><li><span><a href="#배열-형태-변경" data-toc-modified-id="배열-형태-변경-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>배열 형태 변경</a></span><ul class="toc-item"><li><span><a href="#[numpy.ndarray-객체].ravel()" data-toc-modified-id="[numpy.ndarray-객체].ravel()-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>[numpy.ndarray 객체].ravel()</a></span></li><li><span><a href="#[numpy.ndarray-객체].reshape()" data-toc-modified-id="[numpy.ndarray-객체].reshape()-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>[numpy.ndarray 객체].reshape()</a></span></li></ul></li><li><span><a href="#배열-요소-추가-삭제" data-toc-modified-id="배열-요소-추가-삭제-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>배열 요소 추가 삭제</a></span><ul class="toc-item"><li><span><a href="#resize" data-toc-modified-id="resize-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span>resize</a></span></li><li><span><a href="#append" data-toc-modified-id="append-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span>append</a></span><ul class="toc-item"><li><span><a href="#case-1:-axis을-지정하지-않을-경우" data-toc-modified-id="case-1:-axis을-지정하지-않을-경우-4.3.2.1"><span class="toc-item-num">4.3.2.1&nbsp;&nbsp;</span>case 1: axis을 지정하지 않을 경우</a></span></li><li><span><a href="#case-2:-axis=0-지정" data-toc-modified-id="case-2:-axis=0-지정-4.3.2.2"><span class="toc-item-num">4.3.2.2&nbsp;&nbsp;</span>case 2: axis=0 지정</a></span></li><li><span><a href="#case-3:-axis=1-지정" data-toc-modified-id="case-3:-axis=1-지정-4.3.2.3"><span class="toc-item-num">4.3.2.3&nbsp;&nbsp;</span>case 3: axis=1 지정</a></span></li></ul></li><li><span><a href="#insert" data-toc-modified-id="insert-4.3.3"><span class="toc-item-num">4.3.3&nbsp;&nbsp;</span>insert</a></span></li><li><span><a href="#delete" data-toc-modified-id="delete-4.3.4"><span class="toc-item-num">4.3.4&nbsp;&nbsp;</span>delete</a></span></li></ul></li><li><span><a href="#배열-결합" data-toc-modified-id="배열-결합-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>배열 결합</a></span><ul class="toc-item"><li><span><a href="#np.concatenate" data-toc-modified-id="np.concatenate-4.4.1"><span class="toc-item-num">4.4.1&nbsp;&nbsp;</span>np.concatenate</a></span></li><li><span><a href="#np.vstack" data-toc-modified-id="np.vstack-4.4.2"><span class="toc-item-num">4.4.2&nbsp;&nbsp;</span>np.vstack</a></span></li><li><span><a href="#np.hstack" data-toc-modified-id="np.hstack-4.4.3"><span class="toc-item-num">4.4.3&nbsp;&nbsp;</span>np.hstack</a></span></li></ul></li><li><span><a href="#배열-분리" data-toc-modified-id="배열-분리-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>배열 분리</a></span><ul class="toc-item"><li><span><a href="#np.hsplit" data-toc-modified-id="np.hsplit-4.5.1"><span class="toc-item-num">4.5.1&nbsp;&nbsp;</span>np.hsplit</a></span></li><li><span><a href="#np.vsplit" data-toc-modified-id="np.vsplit-4.5.2"><span class="toc-item-num">4.5.2&nbsp;&nbsp;</span>np.vsplit</a></span></li></ul></li></ul></li><li><span><a href="#Reference" data-toc-modified-id="Reference-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reference</a></span></li></ul></div>

In [2]:
import numpy as np

In [3]:
np.random.seed(1234) # 재현성을 위하여

---

## NumPy 배열복사

ndarray 배열 객체에 대한 slice, subset, indexing이 반환하는 배열은 새로운 객체가 아닌 기존 배열의 뷰입니다. 반환한 배열의 값을 변경하면 원본 배열에 반영됩니다. 따라서 기본 배열로부터 새로운 배열을 생성하기 위해서는 copy 함수로 명시적으로 사용해야 합니다. copy 함수로 복사된 원본 배열과 사본 배열은 완전히 다른 별도의 객체입니다.

In [4]:
#데모용 배열
a = np.random.randint(0, 9, (3, 3))
a

array([[3, 6, 5],
       [4, 8, 1],
       [7, 6, 8]])

In [5]:
copied_a1 =np.copy(a)

In [6]:
# 복사된 배열의 요소 업데이트
copied_a1[:, 0]=0 #배열의 전체 row의 첫번째 요소 0으로 업데이트
copied_a1

array([[0, 6, 5],
       [0, 8, 1],
       [0, 6, 8]])

In [8]:
# 복사본 배열 변경이 원보에 영향을 미치지 않음
a

array([[3, 6, 5],
       [4, 8, 1],
       [7, 6, 8]])

In [10]:
#np.copy()를 이용한 복사
copied_a2 = np.copy(a)
copied_a2

array([[3, 6, 5],
       [4, 8, 1],
       [7, 6, 8]])

---

## NumPy 배열 정렬

ndarray 객체는 axis를 기준으로 요소 정렬하는 `sort 함수`를 제공합니다.

In [11]:
#배열 생성
unsorted_arr = np.random.random((3, 3))
unsorted_arr

array([[0.50099513, 0.68346294, 0.71270203],
       [0.37025075, 0.56119619, 0.50308317],
       [0.01376845, 0.77282662, 0.88264119]])

In [12]:
#데모를 위한 배열 복사
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

> [ndarray 객체].sort() axis의 기본 값은 -1입니다.  
> axis=-1은 현재 배열의 마지막 axis를 의미합니다.  
> 현재 unsorted_arr의 마지막 axis는 1입니다.  
> [ndarray 객체].sort()와 [ndarray 객체].sort(axis=1)의 결과는 동일합니다.  

In [14]:
#배열 정렬
unsorted_arr1.sort()
unsorted_arr1

array([[0.50099513, 0.68346294, 0.71270203],
       [0.37025075, 0.50308317, 0.56119619],
       [0.01376845, 0.77282662, 0.88264119]])

In [15]:
#배열 정렬, axis=0 열방향으로 정렬
unsorted_arr2.sort(axis=0)
unsorted_arr2

array([[0.01376845, 0.56119619, 0.50308317],
       [0.37025075, 0.68346294, 0.71270203],
       [0.50099513, 0.77282662, 0.88264119]])

In [16]:
#배열 정렬, axis=1, 행방향으로 정렬
unsorted_arr3.sort(axis=1)
unsorted_arr3

array([[0.50099513, 0.68346294, 0.71270203],
       [0.37025075, 0.50308317, 0.56119619],
       [0.01376845, 0.77282662, 0.88264119]])

---

## 서브셋, 슬라이싱, 인덱싱

###  요소 선택

배열의 각 요소는 axis 인덱스 배열로 참조할 수 있습니다. 1차원 배열은 1개 인덱스, 2차원 배열은 2개 인덱스, 3차원 인덱스는 3개 인덱스로 요소를 참조할 수 있습니다.

인덱스로 참조한 요소는 값 참조, 값 수정이 모두 가능합니다.

In [17]:
# 데모 배열 생성
a0 = np.arange(24) # 1차원 배열
a0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
a1 = np.arange(24).reshape((4, 6)) #2차원 배열
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
a2 = np.arange(24).reshape((2, 4, 3)) # 3차원 배열
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

#### 1 차원 배열 요소 참조 및 변경

In [20]:
a0[5] # 5번 인덱스 요소 참조

5

In [21]:
# 5번 인덱스 요소 업데이트
a0[5] = 1000000

In [22]:
a0

array([      0,       1,       2,       3,       4, 1000000,       6,
             7,       8,       9,      10,      11,      12,      13,
            14,      15,      16,      17,      18,      19,      20,
            21,      22,      23])

#### 2 차원 배열 요소 참조 및 변경

In [23]:
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
# 1행 두번째 컬럼 요소 참조
a1[0, 1]

1

In [25]:
# 1행 두번째 컬럼 요소 업데이트
a1[0, 1]=10000

In [26]:
a1

array([[    0, 10000,     2,     3,     4,     5],
       [    6,     7,     8,     9,    10,    11],
       [   12,    13,    14,    15,    16,    17],
       [   18,    19,    20,    21,    22,    23]])

#### 3 차원 배열 요소 참조 및 변경

In [27]:
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [28]:
# 2 번째 행, 첫번째 컬럼, 두번째 요소 참조
a2[1, 0, 1]

13

In [29]:
a2[1, 0, 1]=10000

In [30]:
a2

array([[[    0,     1,     2],
        [    3,     4,     5],
        [    6,     7,     8],
        [    9,    10,    11]],

       [[   12, 10000,    14],
        [   15,    16,    17],
        [   18,    19,    20],
        [   21,    22,    23]]])

### 슬라이싱

여러개의 배열 요소를 참조할 때 슬라이싱을 사용합니다. 슬라이싱은 axis 별로 범위를 지정하여 실행합니다. 범위는 **from `index` to `index`** 형태로 지정합니다. from_index는 범위의 시작 인덱스이며, to_index는 범위의 종료 인덱스입니다. 요소 범위를 지정할 때 to_index는 결과에 포함되지 않습니다. **from `index` to `index`** 의 범위 지정에서 from_index는 생략 가능합니다. 생략할 경우 0을 지정한 것으로 간주합니다. to_index 역시 생략 가능합니다. 이 경우 마지막 인덱스로 설정됩니다. 따라서 **`:` 형태로 지정된 범위는 전체 범위를 의미**합니다.from_index와 to_index에 음수를 지정하면 이것은 반대 방향을 의미합니다. 예를 들어서 -1은 마지막 인덱스를 의미합니다.

In [31]:
a1 = np.arange(1,25).reshape((4,6))
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [32]:
a1[1:3, 1:5]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [33]:
a1[1:-1, 1:-1]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

#### 슬라이싱 업데이트

In [34]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [35]:
# 슬라이싱 배열
slide_arr = a1[1:3, 1:5]
slide_arr

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [36]:
# 슬라이싱을 적용하여 참조한 4개 요소 업데이트 및 슬라이싱 배열 조회
slide_arr[:, 1:3] = 99999
slide_arr

array([[    8, 99999, 99999,    11],
       [   14, 99999, 99999,    17]])

### 불린 인덱싱(Boolean Indexing)

NumPy는 불린 인덱싱은 배열 각 요소의 선택 여부를 True, False 지정하는 방식입니다. 해당 인덱스의 True만을 조회합니다.

In [37]:
# 데모 배열 생성
a1 = np.arange(1, 25).reshape((4, 6)) #2차원 배열
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [38]:
# 짝수인 요소 확인
# numpy broadcasting을 이용하여 짝수인 배열 요소 확인
even_arr = (a1%2==0)
even_arr

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [39]:
# a1[a1%2==0] 동일한 의미 
a1[even_arr]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [40]:
np.sum(a1)

300

### 팬시 인덱싱(Fancy Indexing)

배열에 인덱스 배열을 전달하여 요소를 참조하는 방법입니다.



In [41]:
arr = np.arange(1, 25).reshape((4, 6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [42]:
# CASE 1
[arr[0,0], arr[1, 1], arr[2, 2], arr[3, 3]]

[1, 8, 15, 22]

In [43]:
# 두 배열을 전달==> (0, 0), (1,1), (2,2), (3, 3)
arr[[0, 1, 2, 3], [0, 1, 2, 3]]

array([ 1,  8, 15, 22])

In [44]:
# CASE 2
# 전체 행에 대해서, 1, 2번 컬럼 참조
arr[:, [1, 2]]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

---

## 배열 변환

배열을 변환하는 방접으로는 전치, 배열 shape 변환, 배열 요소 추가, 배열 결합, 분리 등이 있습니다. 각 배열 변경 방법에 대하여 살펴보겠습니다.

### 전치(Transpose)

- Tranpose는 행렬의 인덱스가 바뀌는 변환입니다. 행렬의 Tranpose의 예는 다음과 같습니다.
- 다음은 NumPy에서 행렬을 전치하기 위하여 [numpy.ndarray 객체]`.T` 속성을 사용합니다.
- 이 속성은 전치된 행렬을 반환합니다.

In [45]:
# 행렬 생성
a = np.random.randint(1, 10, (2, 3))
a

array([[8, 1, 1],
       [4, 3, 4]])

In [46]:
#행렬의 전치
a.T

array([[8, 4],
       [1, 3],
       [1, 4]])

### 배열 형태 변경

- [numpy.ndarray 객체]는 배열의 Shape을 변경하는 ravel 메서드와 reshape 메서드를 제공합니다.

    - ravel은 배열의 shape을 1차원 배열로 만드는 메서드입니다.
    - reshape은 데이터 변경없이 지정된 shape으로 변환하는 메서드입니다.

#### [numpy.ndarray 객체].ravel()

배열을 `1차원 배열로 반환하는 메서드`입니다. numpy.ndarray 배열 객체의 View를 반환합니다. ravel 메서드가 반환하는 배열은 원본 배열이 뷰입니다. 따라서 ravel 메서드가 반환하는 배열의 요소를 수정하면 원본 배열 요소에도 반영됩니다.

In [47]:
# 데모 배열 생성
a = np.random.randint(1, 10, (2, 3))
a

array([[2, 4, 2],
       [4, 8, 2]])

> revel이 반환하는 배열은 a 행렬의 view입니다.  
> 반환 행렬의 데이터를 변경하면 a 행렬도 변경됩니다.

In [48]:
a.ravel()

array([2, 4, 2, 4, 8, 2])

#### [numpy.ndarray 객체].reshape()

- [numpy.ndarray 객체]의 shape을 변경합니다. **실제 데이터를 변경하는 것은 아닙니다.** 배열 객체의 shape 정보만을 수정합니다.

In [50]:
# 대상 행렬 속성 확인
a = np.random.randint(1, 10, (2, 3))
a

array([[5, 1, 9],
       [9, 7, 9]])

In [51]:
a.reshape((3, 2, 1))

array([[[5],
        [1]],

       [[9],
        [9]],

       [[7],
        [9]]])

### 배열 요소 추가 삭제
배열의 요소를 변경, 추가, 삽입 및 삭제하는 resize, append, insert, delete 함수를 제공합니다.



#### resize

- np.resize(a, new_shape)
- np.ndarray.resize(new_shape, refcheck=True)
- 배열의 shape과 크기를 변경합니다.

np.resize와 np.reshape 함수는 배열의 shape을 변경한다는 부분에서 유사합니다. 차이점은 reshape 함수는 배열 요소 수를 변경하지 않습니다. reshape 전후 배열의 요소 수는 같습니다. 반면에 resize는 shape을 변경하는 과정에서 배열 요소 수를 줄이거나 늘립니다.

In [52]:
#배열 생성
a = np.random.randint(1, 10, (2, 6))
a

array([[7, 4, 2, 3, 6, 3],
       [6, 7, 8, 5, 4, 6]])

In [54]:
# shape 변경 - 요소 수 변경 없음
a.resize((6, 2))
a

array([[7, 4],
       [2, 3],
       [6, 3],
       [6, 7],
       [8, 5],
       [4, 6]])

In [56]:
# 요소의 수가 12개에서 20개로 늘어남
# 늘어난 요소는 0으로 채워짐
a = np.random.randint(1, 10, (2, 6))
a.resize((2, 10))
a

array([[7, 5, 7, 3, 5, 3, 8, 8, 8, 3],
       [8, 5, 0, 0, 0, 0, 0, 0, 0, 0]])

In [57]:
#배열 생성
# 요소숙 12개에서 9개로 줄임
# 이전 데이터 삭제
a = np.random.randint(1, 10, (2, 6))
a.resize((3, 3))
a

array([[1, 3, 2],
       [3, 2, 6],
       [8, 5, 8]])

#### append

- np.append(arr, values, axis=None)
- 배열의 끝에 값을 추가
- np.append 함수는 arr의 끝에 values(배열)을 추가합니다. axis로 배열이 추가되는 방향을 지정할 수 있습니다.

In [58]:
# 데모 배열 생성
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

##### case 1: axis을 지정하지 않을 경우

axis를 지정하지 않으면 배열은 1차원 배열로 변형되어 결합됩니다.

In [60]:
# axis 지정 없이 추가
result = np.append(a, b)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [61]:
#원본 배열을 변경하는 것이 아니며 새로운 배열이 생성됩니다. 
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### case 2: axis=0 지정

In [62]:
# axis = 0
# axis 0 방향으로 b 배열 추가
result = np.append(a, b, axis=0)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

> axis = 0 설정 시, shape[0]를 제외한 `나머지 shape은 같아야` 합니다.  
> shape[0]를 제외한 나머지 shape이 다를 경우 append는 오류를 발생합니다.  

##### case 3: axis=1 지정

In [63]:
# axis = 1
# axis 1 방향으로 b 배열 추가
result = np.append(a, b, axis=1)
result

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

#### insert

- np.insert(arr, obj, values, axis=None)
- axis를 지정하지 않으며 1차원 배열로 변환
- 추가할 방향을 axis로 지정

In [64]:
# 데모 배열 생성
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#  a 배열을 일차원 배열로 변환하고 1번 index에 99 추가
np.insert(a, 1, 999)

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [66]:
# a 배열의 axis 0 방향 1번 인덱스에 추가
# index가 1인 row에 999가 추가됨
np.insert(a, 1, 999, axis=0)

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

#### delete

- np.delete(arr, obj, axis=None)
- axis를 지정하지 않으며 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- delete 함수는 원본 배열을 변경하지 않으며 새로운 배열을 반환

In [67]:
# 데모 배열 생성
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#  a 배열을 일차원 배열로 변환하고 1번 index 삭제
np.delete(a, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# a 배열의 axis 1 방향 1번 인덱스인 열을 삭제한 배열을 생성하여 반환
np.delete(a, 1, axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

### 배열 결합

배열과 배열을 결합하는 np.concatenate, np.vstack, np.hstack 함수를 제공합니다.

#### np.concatenate

> concatenate((a1, a2, ...), axis=0)  
> a1, a2....: 배열

In [70]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b = np.arange(7, 13).reshape((2, 3))
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [72]:
# axis=0 방향으로 두 배열 결합, axis 기본값=0
result = np.concatenate((a, b))
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
# axis=0 방향으로 두 배열 결합, 결과 동일
result = np.concatenate((a, b), axis=0)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
# axis=1 방향으로 두 배열 결합, 결과 동일
result = np.concatenate((a, b), axis=1)
result

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### np.vstack

- np.vstack(tup)
- tup: 튜플
- 튜플로 설정된 여러 배열을 수직 방향으로 연결 (axis=0 방향)
- np.concatenate(tup, axis=0)와 동일

In [75]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
b = np.arange(7, 13).reshape((2, 3))

In [76]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
# 4개 배열을 튜플로 설정
np.vstack((a, b, a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.hstack

- np.hstack(tup)
- tup: 튜플
- 튜플로 설정된 여러 배열을 수평 방향으로 연결 (axis=1 방향)
- np.concatenate(tup, axis=1)와 동일

In [78]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
b = np.arange(7, 13).reshape((2, 3))

In [79]:
np.hstack((a, b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [80]:
np.hstack((a, b, a, b))

array([[ 1,  2,  3,  7,  8,  9,  1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12,  4,  5,  6, 10, 11, 12]])

###  배열 분리

NumPy는 배열을 수직, 수평으로 분할하는 함수를 제공합니다.

- np.hsplit(): 지정한 배열을 수평(행) 방향으로 분할
- np.vsplit(): 지정한 배열을 수직(열) 방향으로 분할

#### np.hsplit
- np.hsplit(ary, indices_or_sections)
- 배열을 컬럼 방향으로 분할하는 함수

In [81]:
# 분할 대상 배열 생성
a = np.arange(1, 25).reshape((4, 6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [82]:
# 수평으로 두 그룹으로 분할하는 함수
result = np.hsplit(a, 2)
result

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]), array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [83]:
# 수평으로 두 그룹으로 분할하는 함수
result = np.hsplit(a, 3)
result

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

#### np.vsplit

- np.vsplit(ary, indices_or_sections)
- 배열을 수직 방향(행 방향)으로 분할하는 함수

In [84]:
# 분할 대상 배열 생성
a = np.arange(1, 25).reshape((4, 6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [85]:
result=np.vsplit(a, 2)
result

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [86]:
result=np.vsplit(a, 4)
result

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

---

## Reference

- https://www.intel.com
- https://numpy.org/
- https://github.com/rougier/numpy-tutorial
- https://github.com/rougier/numpy-100
- http://aikorea.org/cs231n/python-numpy-tutorial/
- http://riseshia.github.io/2017/01/30/numpy-tutorial-with-code.html
- https://datascienceschool.net/view-notebook/24e43f9df9ec4abab15e32e68e982cc1/
- http://taewan.kim/post/numpy_cheat_sheet/